---
title: "Awards"
pagetitle: "Mirko Signorelli's awards"
---

### IBC2020's Young Statistician Showcase Award

In August 2020 I received the [**Young Statistician Showcase (YSS) Award of the International Biometric Society**]((https://www.vvsor.nl/biometrics/news/two-awards-for-bms-aned-members-at-ibc2020)) (IBS).

This award was based on a world-wide competition whereby young statisticians could submit a short paper with a contribution to be presented at the 30th International Biometric Conference (IBC2020). Five winners, one for each macroregion of IBS, were selected. My short paper, entitled "How to predict a survival outcome using longitudinal and high-dimensional omics data", was the winner for Europe. Its contents were presented during the [YSS session of IBC2020](https://www.ibc2020.org/scientific-programme/showcases).

### Best PhD Thesis Award

In June 2018 I received the **Best PhD Thesis Award of the Italian Statistical Society**. 

This award is awarded every other year to PhD theses belonging to one of the following categories: methological statistics, applied statistics and demography. My PhD thesis, entitled "Inferring Community-driven Structure in Complex Networks", was selected for the award in the applied statistics category.

After I received the award, I was interviewed by the Italian newspaper *Corriere della Sera*; [you can read the interview (in Italian) here](https://bergamo.corriere.it/notizie/cronaca/18_ottobre_05/da-chiuduno-all-olanda-premiato-la-ricerca-statistica-politica-8bce14cc-c87b-11e8-81ab-863c582a99f0.shtml).

### Best Student Paper Award

In July 2017 I received the [**Best Student Paper Toyota Corporation Award of the Statistical Modelling Society**](https://journals.sagepub.com/doi/full/10.1177/1471082X17726638).

This award was based on a competition between all short papers submitted by PhD students for a contributed talk at the 32nd International Workshop on Statistical Modelling (IWSM).

### Research Award 2016

In 2017 I received the **Research Award 2016 of the Department of Statistics of the University of Padova**.

This award is based on a competition whereby all junior researchers affiliated to the Department of Statistics can submit one of their published articles for consideration. I received the award based on my article [NEAT: an efficient network enrichment analysis test](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-1203-6) that is published in BMC Bioinformatics.
