---
title: "Students"
output:
  html_document:
    toc: true
---

### Prospective students

#### PhD students and postdocs

Feel free to contact me in case

1. you are currently pursuing a PhD or working as postdoc, and would like to explore the possibility of working together;
2. you are looking for a PhD or postdoc position, and would like to inquire about open vacancies or future opportunities.

#### BSc and MSc students

Are you interested in doing your bachelor's / master's thesis project with me? Feel free to get in touch to discuss this possibility!

Before sending me a request for supervision, I would like to ask you to [check out this document](https://github.com/mirkosignorelli/info4supervisions/blob/main/supervision_request.md) where I detail the type of information that I need to be able to assess your request and come up with a project that best fits your profile and our shared interests.

### PhD students

* **Xiang Li** (2025+)  
PhD student in *Statistics*  
Mathematical Institute, Leiden University  

* [Lorenzo Carvisiglia](https://www.unibo.it/sitoweb/lorenzo.carvisiglia/en) (2023+, co-supervisor: Saverio Ranciati)  
PhD student in *Statistics*  
Department of Statistical Sciences, University of Bologna  

* [Daniel Gomon](https://github.com/d-gomon) (2021-25; co-supervisors: Marta Fiocco and Hein Putter)  
PhD student in *Statistics*  
Mathematical Institute, Leiden University  

### Master students

* **Ioannis Liolios** (2024-25)  
MSc in *Mathematics*  
Mathematical Institute, Leiden University  
Thesis title: *Co-clustering on binary hypergraphs*

* **Xiang Li** (2025)  
MSc in *Statistics and Data Science*  
Mathematical Institute, Leiden University  
Thesis title: *A Comparative Study of EstimationTechniques for Generalized Linear Mixed Models*

* **Astrid Stulemeijer** (2023-25; external supervisor: Christian Steglich)  
MSc in *Statistics and Data Science*  
Mathematical Institute, Leiden University + Department of Sociology, University of Groningen  
Thesis title: *Measurement error in longitudinal social network data: the sensitivity of stochastic actor-oriented models*

* **Jelle Hazenbosch** (2023-25; external supervisor: Marjolijn Das)  
MSc in *Statistics and Data Science*  
Mathematical Institute, Leiden University + Centrale Bureau voor de Statistiek  
Thesis title: *Using registration data to evaluate social induction of solar panel adoption*

* **Eugenia Driusso** (2023-24; internal supervisor: Alessandra Brazzale, co-supervisor: Ernst Wit)  
MSc in *Statistical Science*  
Mathematical Institute, Leiden University + Department of Statistics, University of Padova  
Thesis title: *Statistical modelling of time-stamped hypergraphs: a model-based clustering approach*

* **Lana Broer** (2023-24; external supervisor: Alessio Crippa)  
MSc in *Statistics and Data Science*  
Mathematical Institute, Leiden University + Department of Medical Epidemiology and Biostatistics, Karolinska Institute  
Thesis title: *Investigating the prognostic value of prostate-specific antigen in metastatic prostate cancer: a joint modeling and landmark approach*

* **Sophie Retif** (2022-23; internal supervisor: Francesca Ieva)  
MSc in *Mathematical Engineering*  
Mathematical Institute, Leiden University + Department of Mathematics, Politecnico di Milano, Milan   
Thesis title: *Dynamic prediction of survival with many longitudinal predictors: an empirical evaluation*

* **Henk van der Pol** (2022-23)  
MSc in *Mathematics*  
Mathematical Institute, Leiden University  
Project title: *A comparison of methods for the selection of the tuning parameters in penalized regression* 

* **Yibin Feng** (2022)  
MSc in *Statistics and Data Science*  
Mathematical Institute, Leiden University  
Thesis title: *An empirical evaluation of methods for the prediction of survival with many longitudinally-measured predictors*

* **Gergely Talyigas** (2021;  co-supervisor: Marta Fiocco)  
MSc in *Statistics for the Life and Behavioural Sciences*  
Mathematical Institute, Leiden University  
Thesis title: *A systematic comparison of methods for the validation of binary classification models*

* **Frank Lefeber** (2017; co-supervisor: Ernst Wit)    
MSc in *Education and Communication in Mathematics and Natural Sciences*  
Johann Bernoulli Institute for Mathematics and Computer Science, University of Groningen  
Thesis title: *Heterogeneity for the Stochastic Blockmodel and the Issue of Separation in Political Networks*

* **Harmen Dijkstra** (2016; co-supervisor: Ernst Wit)  
MSc in *Mathematics*  
Johann Bernoulli Institute for Mathematics and Computer Science, University of Groningen  
Thesis title: *Generalized linear models for network analysis*  

### Bachelor students

* **Wouter Ockers** (2025)  
BSc in *Mathematics*  
Mathematical Institute, Leiden University  
Thesis title: *A comparative study of estimation methods for clustered data: Evaluating the GLMM and HGLM frameworks*

* **Jana Krabbendam** (2025; co-supervisor: Pietro Spitali)  
BSc in *Mathematics*  
Mathematical Institute, Leiden University + Department of Human Genetics, Leiden University Medical Center  
Thesis title: *Identifying Potential Biomarkers for Duchenne Muscular Dystrophy in Urinary Metabolomics Data*  

* **Eva Rovan** (2022-24; co-supervisor: Salvatore Battaglia)  
BSc in *Mathematics*  
Mathematical Institute, Leiden University  
Thesis title: *In the Shadows of History: A Competing Risks Analysis of Child Mortality in 19th Century Amsterdam*

<!-- the part below is a fix to the menu not displaying properly
on the mobile version -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>