---
title: "Talks"
pagetitle: "Mirko Signorelli's list of presentations"
output:
  html_document:
    toc: true
---

### Invited talks

<ol reversed class="spacedList">

<li> "What's cooking in the dynamic prediction pot". 
[Dynalife BioNetworks Workshop](https://www.dynalife.eu/cetinje-2025), Cetinje (ME), Jul. 2025
</li>

<li> "Dynamic prediction with numerous longitudinal covariates made easy: the R package pencal". 
[18th International Conference on Computational and Methodological Statistics (CMStatistics2024)](https://www.cmstatistics.org/CFECMStatistics2024/index.php), London (UK), Dec. 2024
</li>

<li> "Statistical methods for the dynamic prediction of survival in settings with numerous longitudinal predictors". 
Department of Statistics, University of Padova (IT), Apr. 2024
</li>

<li> "Model-based clustering for populations of networks". 
Department of Economics, Business and Statistics, University of Palermo (IT), Mar. 2023
</li>

<li> "Pencal: a method to predict survival from longitudinal and high-dimensional (omic) data". 
[13th Conference of the Italian region of the International Biometric Society](https://ibs-italy.org/?page_id=1349&lang=it), Sep. 2021.
</li>

<li> "How to predict a survival outcome using longitudinal and high-dimensional omics data". 
[Young Statistician Showcase](https://www.ibc2020.org/scientific-programme/showcases) of the [30th International Biometric Conference](https://www.ibc2020.org/home), Aug. 2020. [Recording of the talk](https://www.youtube.com/watch?v=wRKqmo2U-sc&t=2485s).  
<span style="color: orchid;">
I was invited to give this presentation at IBC2020's Young Statistician Showcase after winning the [Young Statistician Award of the International Biometric Society](awards.html) with a short article that briefly illustrated the Penalized Regression Calibration method.
</span>
</li>

<li> "Predicting time to loss of ambulation for Duchenne patients using longitudinal, high-dimensional omic data". 
[Symposium on methods for the analysis of complex and multiomics data](https://www.bigstatistics.nl/integration-symposium-1), VUMC, Amsterdam (NL), Sep. 2019.
</li>

<li> "Inferring community-driven structure in complex networks". 
[49th Scientific meeting of the Italian Statistical Society](http://meetings3.sis-statistica.org/index.php/sis2018), Palermo (IT), June 2018.  
<span style="color: orchid;">
I was invited to give this presentation at the Scientific meeting of the Italian Statistical Society (SIS) after winning the [Best PhD Thesis Award from SIS](awards.html) in the category Applied Statistics.
</span>
</li>

<li> "Variable selection for (realistic) stochastic blockmodels". 
[SIS2017 conference on "Statistics and Data Science: New Challenges, New Generations"](http://meetings3.sis-statistica.org/index.php/sis2017/sis2017), Florence (IT), June 2017.
</li>

<li> "Comparing community structures in complex networks". 
Department of Computer Science, University of Sheffield (UK), Feb. 2017.
</li>

<li> "Comparing community structures in complex networks". 
University of Manchester (UK), Feb. 2017.
</li>

<li> "Reconstructing collaborations between political parties from bill cosponsorship networks". 
1st meeting of the [European Cooperation for Statistics of Network Data Science](http://www.cost.eu/COST_Actions/ca/CA15109), Ribno (SL), September 2016.
</li>

<li> "Modelling community structure in the Italian Parliament: a penalized inference approach".
[Workshop on "Network Science and its applications"](https://www.newton.ac.uk/event/snaw02), Isaac Newton Institute, Cambridge (UK), August 2016.
</li>

</ol>

### Contributed talks

<ol reversed class="spacedList">

<li> "Dynamic prediction with numerous longitudinal predictors: how to combine the best of both worlds (landmarking and joint modelling) through penalized regression calibration". 
[10th Survival Analysis for Junior Researchers conference](https://safjr2025.uni-bonn.de), Bonn (GE), March 2025.
</li>

<li> "A critical appraisal of recent developments in the methodology for the dynamic prediction of survival". 
[Bernoulli-IMS 11$^{th}$ World Congress in Probability and Statistics](https://www.bernoulli-ims-worldcongress2024.org), Ruhr University Bochum, Bochum (GE), Aug. 2024 
</li>

<li> "Dynamic Prediction with Numerous Longitudinal Covatiates". [UseR!2024](https://events.linuxfoundation.org/user/), Salzburg (AT), July 2024
</li>

<li> "pencal: an R package for the dynamic prediction of survival with many longitudinal predictors".
[16th International Conference on Computational and Methodological Statistics (CMStatistics2023)](http://www.cmstatistics.org/CMStatistics2023/index.php), Berlin (GE), Dec. 2023
</li>

<li> "Handling many longitudinal predictors in survival analysis: a penalized regression calibration approach". 
[34th European Meeting of Statisticians (EMS2023)](https://ems2023.org), University of Warsaw, Warsaw (PL), July 2023.
</li>

<li> "Analysing populations of networks with mixtures of generalized linear mixed models". 
[24th International Conference on Computational Statistics (COMPSTAT2022)](http://www.compstat2022.org), University of Bologna, Bologna (IT), Aug. 2022.
</li>

<li> "Penalized Regression Calibration: a statistical method to predict survival from longitudinal and high-dimensional omic data". 
[31st International Biometric Conference](https://www.ibc2022.org/home), Riga (LV), July 2022.
</li>

<li> "Penalized regression calibration: a method for the prediction of survival outcomes using complex longitudinal and high-dimensional data".
[8th Channel Network conference](https://cnc21.sciencesconf.org/), Apr. 2021.
</li>

<li> "How to predict a survival outcome using longitudinal and high-dimensional omic data".
[41st Conference of the International Society for Clinical Biostatistics](https://iscb2020.info/), Aug. 2020.
</li>

<li> "ptmixed: an R package for flexible modelling of longitudinal overdispersed count data".
[European R users meeting (e-Rum2020)](https://2020.erum.io), June 2020. [Recording of the talk](https://www.youtube.com/watch?v=79lUgThZ4HE&t=738s).
</li>

<li> "From NEAT to NEWTON: ideas on how to eradicate dichotomania in network enrichment analysis".
[COSTNET Early Career Training Event](https://www.en.wisostat.statistik.uni-muenchen.de/research/workshop/costnet/index.html), Ludwig Maximilian University, Munich (GE), February 2019.
</li>

<li> "Model-based clustering for populations of networks". 
[COSTNET18 conference](http://costnet18.wzim.sggw.pl/), Warsaw (PL), September 2018.
</li>

<li> "On a flexible model for longitudinal RNA-seq data: the Poisson-Tweedie mixed effects model". 
[29th International Biometric Conference](http://2018.biometricconference.org), Barcellona (SP), July 2018.
</li>

<li> "Community detection in networks: shall we bother about metadata?". 
[COSTNET Sandpit meeting](https://www.stats.ox.ac.uk/events/costnet18), Department of Statistics, Oxford (UK), March 2018.
</li>

<li> "How to integrate gene enrichment analysis with information from gene interaction networks".
[COSTNET17 conference](http://costnet.webhosting.rug.nl/dokuwiki/doku.php?id=ev:2017:pdm), IFISC, Palma de Mallorca (SP), October 2017.
</li>

<li> "Model-based clustering for populations of networks". 
[32nd International Workshop on Statistical Modelling](https://iwsm2017.webhosting.rug.nl), Groningen (NL), July 2017.  
<span style="color: orchid;">
I received the [Best Student Paper Toyota Corporation Award of the Statistical Modelling Society](awards.html) for the conference proceedings article associated to this presentation.
</span>
</li>

<li> "NEAT: an efficient Network Enrichment Analysis Test". 
[31st International Workshop on Statistical Modelling](https://iwsm2017.webhosting.rug.nl), INSA, Rennes (FR), July 2016.
</li>

</ol>

### Poster presentations

<ol reversed class="spacedList">

<li> "Dynamic prediction of survival with many longitudinal covariates: a review and empirical comparison". 
[9th Survival Analysis for Junior Researchers conference](https://www.uni-ulm.de/mawi/statistics/upcoming-events/safjr2023), Reisenburg (GE), September 2023.
</li>

<li> "Inferring Community-driven Structure in Complex Networks". 
[SemStat Winter School "Statistical Network Science"](https://www.eurandom.tue.nl/events/workshops/2017/SEMSTAT/SEMSTAT_index.html), Eurandom, Eindhoven (NL), March 2017.
</li>

<li> "PNEA: a parametric test for network enrichment analysis". 
[44th annual Meeting of Dutch Statisticians and Probabilists](https://homepages.cwi.nl/~colette/lunteren2015.html), Lunteren (NL), November 2015.
</li>

</ol>

<!-- the part below is a fix to the menu not displaying properly on the mobile version -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>