---
title: "Teaching"
output:
  html_document:
    toc: true
---

### Active courses

#### Computational Statistics and Longitudinal Data Analysis (2025 - now)

Bachelor's programme in *Mathematics (Wiskunde)* and Master's programme in *Mathematics* (this is a "Bachelor-Master" course)  
Mathematical Institute, Leiden University

* 2025 course info: TBA

#### Computational Statistics (2024 - now)

Master's programme in *Statistics \& Data Science*  
Mathematical Institute, Leiden University

* [2025 course info](https://studiegids.universiteitleiden.nl/en/courses/123870/computational-statistics)
* [2024 course info](https://studiegids.universiteitleiden.nl/en/courses/122111/computational-statistics)

### Past courses

#### Onderwerpen in de Statistiek / Topics in Statistics: module on Longitudinal Data Analysis and GLMMs (2025)

Bachelor's programme in *Mathematics (Wiskunde)*  
Mathematical Institute, Leiden University

* [2025 course info](https://studiegids.universiteitleiden.nl/courses/129970/onderwerpen-in-de-statistiek)

#### Statistical Computing with R (2021 - 2024)

Master's programme in *Statistics \& Data Science*  
Mathematical Institute, Leiden University

* [2024 course info](https://studiegids.universiteitleiden.nl/en/courses/124033/statistical-computing-with-r)
* [2023 course info](https://studiegids.universiteitleiden.nl/en/courses/121707/statistical-computing-with-r)
* [2022 course info](https://studiegids.universiteitleiden.nl/en/courses/115518/statistical-computing-with-r)
* [2021 course info](https://studiegids.universiteitleiden.nl/en/courses/110098/statistical-computing-with-r)

#### Advanced Statistical Computing (2021 - 2023)

Master's programme in *Statistics \& Data Science*  
Mathematical Institute, Leiden University

* [2023 course info](https://studiegids.universiteitleiden.nl/en/courses/114185/advanced-statistical-computing)
* [2022 course info](https://studiegids.universiteitleiden.nl/en/courses/114185/advanced-statistical-computing)
* [2021  course info](https://studiegids.universiteitleiden.nl/en/courses/105113/advanced-statistical-computing)

#### Mathematical Statistics 2: module on Longitudinal Data Analysis and GLMMs (2022 - 2024)

Bachelor's programme in *Mathematics (Wiskunde)*  
Mathematical Institute, Leiden University

* [2024 course info](https://studiegids.universiteitleiden.nl/en/courses/118249/mathematical-statistics-2)
* [2023 course info](https://studiegids.universiteitleiden.nl/en/courses/115390/mathematical-statistics-2)
* [2022 course info](https://studiegids.universiteitleiden.nl/en/courses/109613/mathematical-statistics-2)

#### Courses up until 2021

Up until 2021, I worked as teaching assistant for the following courses:

* **Statistics and Probability** (2017-2021)  
Master's programme in *Statistics for the Life and Behavioural Sciences*  
Mathematical Institute, Leiden University

* **Analysis of repeated measurements** (2018)  
Boerhaave Nascholing foundation  
Leiden University Medical Center

* **Basic methods and reasoning in biostatistics** (2017-2019)  
Boerhaave Nascholing foundation  
Leiden University Medical Center

* **Clinical Research in Practice** (2019-2020)  
Master's programme in *Biomedical Sciences*  
Leiden University Medical Center

* **Design and Analysis of Biomedical Studies** (2019-2020)  
Bachelor's programme in *Biomedical Sciences*  
Leiden University Medical Center

* **Methoden en Technieken** (2021)  
Bachelor's programme in *Biomedical Sciences*  
Leiden University Medical Center

* **Statistics II** (2012-2013)  
Master's programmes in *Biostatistics and Experimental Statistics*, and in *Statistics and Economics*  
Faculty of Statistics, University of Milano-Bicocca


<!-- the part below is a fix to the menu not displaying properly
on the mobile version -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>